### ISSUE TITLE
Typescript problem - Expected 1 arguments, but got 2

### ISSUE THREAD

**Issue by Quimy** [webkong/vue3-i18n#10]
Does the function I18nInstance.t have the correct signature? I think as a second param it should take object or am I missing something?

**Comment by webkong** [comment]
Pls Post more code to me.
You can find in types file.

**Comment by Quimy** [comment]
The function t seems to luck second parameter:
https://github.com/webkong/vue3-i18n/blob/b4589683808b710511e02f67f889f5c7fe8225f8/src/types.ts#L14

**Comment by webkong** [comment]
Fixed
