### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by CoolS2** [webkong/vue3-i18n#5]
After updating the module, the following compilation error appeared:

This dependency was not found:

* vue3-i18n in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=script&lang=js,
./src/locales/i18n.js

  "dependencies": {
    "core-js": "^3.6.5",
    "register-service-worker": "^1.7.1",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0",
    "animejs": "^3.2.1",
    "vuex-persistedstate": "^4.0.0",
    "vue3-i18n": "^1.1.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "node-sass": "^4.12.0",
    "sass-loader": "^8.0.2"
  },

**Comment by webkong** [comment]
@CoolS2 Fixed.
