### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by jharveys** [webkong/vue3-i18n#7]
When I tried to install and run your vue js in your example folder, I've got this error message:

` ERROR  Failed to compile with 1 error               
This dependency was not found:

* vue3-i18n in ./src/i18n/index.js

To install it, you can run: npm install --save vue3-i18n
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'`

......but the component is installed !

I have no clue. :(

**Comment by webkong** [comment]
@jharveys Fixed.
